### ISSUE TITLE
History is missing

### ISSUE THREAD

**Issue by g2p** [sapo/kyoto#1]
Consider rebasing on top of
- https://github.com/g2p/kyotocabinet/commits/upstream
- https://github.com/g2p/kyototycoon/commits/upstream 

Those branches use git import-tar to get the full tarball history.
This should help you merge other forks, such as cloudflare's.

**Comment by carlosefr** [comment]
Can you elaborate on that?

I don't find very important to have the tarball release history (although it would be interesting to have the full commit history, if that happened to be made public). Also, we are keeping both cabinet and tycoon in the same repo to make them easier to build/install.
