### ISSUE TITLE
Fails to build on Slackware64 14.1

### ISSUE THREAD

**Issue by zoot** [sapo/kyoto#13]
Hello

Firstly, thanks for sharing your additions to FAL Labs' work on Kyto Cabinet and Tycoon.

I'm unable to build master (commit 87287b8) on Slackware64 14.1.

```
GCC 4.8.2
GLIBC 2.17
```

Firstly, I had to patch your Makefile to permit custom Lua installation paths:

```
--- kyoto-87287b8/Makefile  2016-03-29 16:39:20.000000000 +0000
+++ kyoto-patched/Makefile  2016-05-13 19:04:07.092561610 +0000
@@ -7,6 +7,7 @@
 DESTDIR =
 OS := $(shell uname -s)
 NPROCS = 1
+LUA_ROOT ?= /usr
 CONFIG_FLAGS =


@@ -55,7 +56,7 @@
    $(eval CABINET_ROOT := $(shell awk '/^prefix *=/ {print $$3}' kyotocabinet/Makefile))
    test -x kyototycoon/configure && cd kyototycoon && \
    PKG_CONFIG_PATH="../kyotocabinet" CPPFLAGS="-I../kyotocabinet" LDFLAGS="-L../kyotocabinet" \
-   ./configure --prefix="$(PREFIX)" --with-kc="$(CABINET_ROOT)" --enable-lua $(CONFIG_FLAGS)
+   ./configure --prefix="$(PREFIX)" --with-kc="$(CABINET_ROOT)" --enable-lua --with-lua="$(LUA_ROOT)" $(CONFIG_FLAGS)

 tycoon: kyototycoon/Makefile
    $(MAKE) -j$(NPROCS) -C kyototycoon
```

It would be a welcome addition to your Makefile.

Then, an attempt to build with:

`make PREFIX=/pkg/kyoto/20160329 LUA_ROOT=/pkg/lua/5.1.5`

Ended in failure, as follows:

```
  -L../kyotocabinet -L. -L/pkg/kyoto/20160329/lib -L/usr/local/lib -L/pkg/kyoto/20160329/lib -L/pkg/lua/5.1.5/lib -Wl,-rpath-link,.:/usr/local/lib:.:/usr/local/lib::/pkg/kyoto/20160329/lib:/pkg/lua/5.1.5/lib -Wl,--as-needed  -lkyototycoon -lkyotocabinet -llua
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: /pkg/lua/5.1.5/lib/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[1]: *** [ktserver] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/admin/src/kyoto-master/kyototycoon'
make: *** [tycoon] Error 2
```

I'd greatly appreciate it if you'd help troubleshoot this build.

Let me know if you require further information.

Thanks.

**Comment by zoot** [comment]
I've managed to build both kyotocabinet ...

```
cd kyotocabinet
./configure --prefix=/pkg/kyotocabinet/1.2.76
make
make install
```

and kyototycoon ...

```
cd ../kyototycoon
./configure --prefix=/pkg/kyototycoon/0.9.56 --with-kc=/pkg/kyotocabinet --enable-lua --with-lua=/pkg/lua/5.1.5
make
make install
```

So, bypassing the merged build method, it works.

I suspect my original patch didn't make the anticipated change which was supposed to point the build to the lua base properly ....

**Comment by carlosefr** [comment]
From you snippet I can't see what was being linked when the error popped up. However, the error itself point to a missing `-ldl`.

The difference when you build the two bits separately is that you're installing cabinet before building tycoon. The `Makefile` passes a few environment variables to `configure` to be able to build them in sequence. You can try putting a `-ldl` in `LDFLAGS`.

**Comment by carlosefr** [comment]
Just a small note: the build process tries to find Lua in a few places in order to build without extra options in most popular platforms. Allowing non-standard Lua locations should keep this feature so I suggest adding `--with-lua` conditionally, only when `LUA_ROOT` is non-empty.
