### ISSUE TITLE
configure: error: lua.h is required on Debian 8.6

### ISSUE THREAD

**Issue by sunra** [sapo/kyoto#17]
**liblua50-dev, liblualib50-dev** already installed

I not need Lua scripting, so i remove "--enable-lua" in /Makefile to make successful compilation.

**Comment by carlosefr** [comment]
To build on Debian you need to have `liblua5.1-0-dev` and `liblua5.1-0` installed. Kyoto requires Lua **5.1** and the packages you mention are for Lua **5.0** (which is not compatible).

Packages for both Lua versions can be installed side-by-side, no need to remove the ones you already have.

If you build Debian packages for Kyoto (`make deb`) you'll notice the build process complaining about the missing packages I mentioned above.
